## Example:
Write a code implementing Givens Rotations for QR decomposition. 
Compare two methods for computing the QR decomposition of a matrix:
(1) Givens rotations;
(2) The built-in function np.linalg.qr().


In [3]:
import numpy as np

def givens_rotation(a, b):
    """Computes the cosine and sine for a Givens rotation."""
    if b == 0:
        c, s = 1, 0
    else:
        r = np.hypot(a, b)  # Computes sqrt(a^2 + b^2) in a stable way
        c = a / r
        s = -b / r
    return c, s

def qr_givens(A):
    """Computes the QR decomposition of A using Givens rotations."""
    m, n = A.shape
    Q = np.eye(m)  # Initialize as identity matrix
    R = A.copy().astype(float)

    for j in range(n):  # Iterate over columns
        for i in range(j+1, m):  # Iterate over rows below diagonal
            c, s = givens_rotation(R[j, j], R[i, j])

            # Apply rotation to R
            G = np.eye(m)
            G[[j, i], [j, i]] = c
            G[i, j], G[j, i] = s, -s
            
            R = G @ R  # Rotate R
            Q = Q @ G.T  # Accumulate Q

    return Q, R

# Example matrix
A = np.array([[4, 3],
              [6, 3],
              [8, 6]], dtype=float)

# Compute QR using Givens rotations
Q_givens, R_givens = qr_givens(A)

# Compute QR using NumPy's built-in function
Q_numpy, R_numpy = np.linalg.qr(A)

# Print results
print("=== Givens Rotation QR ===")
print("Q matrix:\n", np.round(Q_givens, 6))
print("R matrix:\n", np.round(R_givens, 6))

print("\n=== NumPy QR ===")
print("Q matrix:\n", np.round(Q_numpy, 6))
print("R matrix:\n", np.round(R_numpy, 6))

# Verify orthogonality
print("\nChecking Orthogonality (Q^T Q ≈ I):")
print("Givens Q^T Q:\n", np.round(Q_givens.T @ Q_givens, 6))
print("NumPy Q^T Q:\n", np.round(Q_numpy.T @ Q_numpy, 6))

# Verify QR reconstruction
print("\nChecking Reconstruction (Q @ R ≈ A):")
print("Givens Q @ R:\n", np.round(Q_givens @ R_givens, 6))
print("NumPy Q @ R:\n", np.round(Q_numpy @ R_numpy, 6))


=== Givens Rotation QR ===
Q matrix:
 [[ 0.3714  0.2491  0.8944]
 [ 0.5571 -0.8305 -0.    ]
 [ 0.7428  0.4983 -0.4472]]
R matrix:
 [[10.7703  7.2421]
 [ 0.      1.2457]
 [-0.     -0.    ]]

=== NumPy QR ===
Q matrix:
 [[-0.3714  0.2491]
 [-0.5571 -0.8305]
 [-0.7428  0.4983]]
R matrix:
 [[-10.7703  -7.2421]
 [  0.       1.2457]]

Checking Orthogonality (Q^T Q ≈ I):
Givens Q^T Q:
 [[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
NumPy Q^T Q:
 [[1. 0.]
 [0. 1.]]

Checking Reconstruction (Q @ R ≈ A):
Givens Q @ R:
 [[4. 3.]
 [6. 3.]
 [8. 6.]]
NumPy Q @ R:
 [[4. 3.]
 [6. 3.]
 [8. 6.]]
