# A zoo of matrices

In [2]:
import numpy as np

In [3]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

[[ 0.77136049 -1.1416175  -0.40210297  1.12909448  0.01882389]
 [ 1.84760193  0.64178    -0.50957619  1.27432583  0.02772194]
 [ 0.75837636  0.09502293  0.11255502 -0.65800371  0.06408541]
 [-0.73401575  0.95601197  1.00376509 -0.36669902 -1.08818232]
 [ 1.26622255 -0.58848242  0.86911581 -0.81824461  0.54127369]]
 
[[ 1.25402979 -0.97948697]
 [-0.1954763   1.5222131 ]
 [-1.09345748  0.42357089]
 [-1.89921541 -1.74966686]
 [ 1.06219106  0.60921375]]


In [4]:
# identity
I = np.eye(5)
print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# zeros
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [7]:
# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
# in matrix C, first two columns are from A and the other four are from B
C = np.concatenate((A,B),axis=1)
print(A),print(' ')
print(B), print(' ')
print(C)

[[-1.56915456  0.95339689]
 [-2.07558761 -0.84558344]
 [-0.87039298  0.93613996]]
 
[[ 0.97481981  0.45242157 -1.91678644 -0.44520637]
 [-0.00603833  0.49444199  0.67678992  0.06646386]
 [ 0.67433722 -0.1062893  -0.01686546  0.24379164]]
 
[[-1.56915456  0.95339689  0.97481981  0.45242157 -1.91678644 -0.44520637]
 [-2.07558761 -0.84558344 -0.00603833  0.49444199  0.67678992  0.06646386]
 [-0.87039298  0.93613996  0.67433722 -0.1062893  -0.01686546  0.24379164]]


In [8]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(S),print(' ')
print(L), print(' ')
print(U)

[[ 0.28332695 -0.85259875 -1.45165093 -1.17380683 -0.05451803]
 [-0.24163684 -1.3323696  -0.05456673 -0.70830091 -0.78561181]
 [ 0.38159678  0.13030734  0.01002444 -0.43269597  1.51135919]
 [-0.37091133 -1.40657118  0.86919426 -3.5362131  -0.23940667]
 [-0.53902622 -2.24447878  0.64900237  1.47412808  0.79056078]]
 
[[ 0.28332695  0.          0.          0.          0.        ]
 [-0.24163684 -1.3323696   0.          0.          0.        ]
 [ 0.38159678  0.13030734  0.01002444  0.          0.        ]
 [-0.37091133 -1.40657118  0.86919426 -3.5362131   0.        ]
 [-0.53902622 -2.24447878  0.64900237  1.47412808  0.79056078]]
 
[[ 0.28332695 -0.85259875 -1.45165093 -1.17380683 -0.05451803]
 [ 0.         -1.3323696  -0.05456673 -0.70830091 -0.78561181]
 [ 0.          0.          0.01002444 -0.43269597  1.51135919]
 [ 0.          0.          0.         -3.5362131  -0.23940667]
 [ 0.          0.          0.          0.          0.79056078]]



---
# Matrix addition and subtraction
---


In [9]:
# create  matrices
A = np.array([ [1, 2], [3, 4] ])
B = np.array([ [5,6], [7,8] ])
C = np.array([ [9,10],[11,12] ])

# add or subtract them
M1=A+B
M2=A-C
print(M1), print(' ')
print(M2)

[[ 6  8]
 [10 12]]
 
[[-8 -8]
 [-8 -8]]



---
# Matrix-scalar multiplication
---


In [10]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# Transpose

In [11]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]



---
# Extract the diagonal.  Trace of a matrix
---


In [12]:

M = np.round(6* np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d), print('')
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[ -4.   1.   1.  -4.]
 [ -5.  14.  -0. -10.]
 [ -1.  -0.  -0.   5.]
 [  2.  -4.   3.  -3.]]
 
[-4. 14. -0. -3.]

[[-4.  0.  0.  0.]
 [ 0. 14.  0.  0.]
 [ 0.  0. -0.  0.]
 [ 0.  0.  0. -3.]]
7.0 7.0



---
# Broadcasting matrix arithmetic
---


In [13]:
# create a matrix
# arrange numbers from 1 to 13 in a 3x4 matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [14]:
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
#print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]


# "Shifting" a matrix: M=A+rI

In [15]:
# "shifting" a matrix
r = .03 # scalar
A = np.array([[4,5,1],[0,1,11],[4,9,7]]) # can only shift a square matrix
M = A + r*np.eye(len(A))
print(A), print(' ')
print(M)

[[ 4  5  1]
 [ 0  1 11]
 [ 4  9  7]]
 
[[ 4.03  5.    1.  ]
 [ 0.    1.03 11.  ]
 [ 4.    9.    7.03]]


# Hadamard multiplication

In [16]:
# two random matrices
A = np.random.randn(3,4)
B = np.random.randn(3,4)

# this is Hadamard multiplication
C1=A*B 
print(A*B),print('')
# and so is this
C2=np.multiply(A,B)
print(C2), print('')

# this one is NOT Hadamard multiplication
# this is just a prodict of A and B^{T}
A@B.T
print(A@B.T)


[[-0.09501445 -0.2831122  -0.55963663  0.09930509]
 [-0.04657312  0.65589408 -0.33890836  0.18260936]
 [-1.30508792  0.68043781 -1.20128492  0.61506991]]

[[-0.09501445 -0.2831122  -0.55963663  0.09930509]
 [-0.04657312  0.65589408 -0.33890836  0.18260936]
 [-1.30508792  0.68043781 -1.20128492  0.61506991]]

[[-0.83845819 -0.41820252 -2.06678685]
 [ 1.34175502  0.45302195  0.64974146]
 [ 0.88111008  3.14605079 -1.21086513]]


# "Standard" matrix multiplication

In [17]:
# Create a few matrices
A = np.random.randn(3,6)
B = np.random.randn(6,4)
C = np.random.randn(6,4)

# try some multiplications, and print out the shape of the product matrix
print( (A@B).shape )
print( np.dot(A,B).shape ) # same as above
print( (B@C.T).shape )
print( (A@C).shape )

(3, 4)
(3, 4)
(6, 6)
(3, 4)


In [18]:
# "standard" multiplication of A and B
S1=A@B
print(S1)

[[-0.12868598 -0.48420211  4.11189521 -2.3002898 ]
 [-0.82620432  1.711716   -3.13996567 -2.63490605]
 [-0.09147906 -0.98122623  4.35677501 -3.53598867]]


In [19]:
# Also "standard" multiplication of A and B
S2=np.dot(A,B)
print (S2)

[[-0.12868598 -0.48420211  4.11189521 -2.3002898 ]
 [-0.82620432  1.711716   -3.13996567 -2.63490605]
 [-0.09147906 -0.98122623  4.35677501 -3.53598867]]


In [20]:
# "standard" product of B and the transpose of C
S3=B@C.T
print(S3)

[[ 0.21128226 -0.61312016  1.6974008   0.09185661  2.55223249  3.13384599]
 [-0.31812982 -1.34539825  0.92581505  0.47705362  5.13962203  3.5439983 ]
 [ 0.10937366 -1.00512344 -0.97711888  0.54340679 -0.96953811 -3.60763332]
 [ 0.72226309 -0.54569479  0.43478633 -0.14775805 -3.07195974 -1.59942595]
 [-0.07860446  0.62542292 -0.16592464 -0.31635978 -0.75653092  0.45762187]
 [-0.18555945  1.2596988  -0.68255695 -0.56724414 -1.92377964  0.01946752]]


# Slicing out rows and columns

In [21]:
# create a matrix
A = np.reshape(np.arange(60),(6,10))
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [22]:
# get the n-th row (in this example the 2nd row)

print( A[1,:] )

# note that to extract only one row, you don't need the column indices. 
print( A[1] )
# But that's potentially confusing, so I recommend avoiding that notation.

[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]


In [23]:
# get the n-th column (in this example the 2nd column)
print( A[:,1] )
# Note that it prints out as a "row" even thought it's a column of the matrix

[ 1 11 21 31 41 51]


In [24]:
# multiple rows
A[0:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [25]:
# multiple columns
A[:,7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49],
       [57, 58, 59]])

In [26]:
# extract a submatrix from rows 2-4 and columns 1-5 
sub = A[1:4:1,0:5:1]

# print them out
print('Original matrix:\n')
print(A)

print('\n\nSubmatrix:\n')
print(sub)

Original matrix:

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


Submatrix:

[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
